version: "3.9"
services:
  db:
    container_name: dafne_db
    hostname: dafne_db
    restart: always
    image: "library/postgres:17"
    env_file:
      - /data/dafne/back-end/config/db_credentials.env
    networks:
      - dafne
    ports:
      - "5432:5432"
    volumes:
      - /data/dafne-db/:/var/lib/postgresql/data
networks:
    dafne:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.16.0.0/16
